[versions]

version-kotlin-bom = "1.9.25"

version-plugin-agp = "8.7.1"
version-plugin-google = "4.4.2"
version-plugin-crashlytics = "3.0.2"

version-androidx-multidex = "2.0.1"
version-androidx-appcompat = "1.2.0"
version-androidx-media = "1.6.0"
version-androidx-constraint = "2.0.4"
version-androidx-lifecycle = "2.2.0"

version-firebase-billOfMaterials = "33.5.1"

version-library-exoplayer = "2.13.3"
version-library-leak = "2.14"
version-library-ktx = "1.3.2"
version-library-material-dialogs = "3.3.0"
version-library-timber = "5.0.1"
material = "1.12.0"

# Test dependencies
version-junit = "4.13.2"
version-mockk = "1.13.8"
version-robolectric = "4.11.1"
version-androidx-test-core = "1.5.0"
version-androidx-test-runner = "1.5.2"
version-androidx-test-rules = "1.5.0"
version-androidx-test-ext-junit = "1.1.5"
version-espresso = "3.5.1"
version-androidx-arch-core = "2.2.0"
version-coroutines-test = "1.7.3"
version-androidx-fragment-testing = "1.6.2"

[libraries]

firebase-billOfMaterials = { module = "com.google.firebase:firebase-bom", version.ref = "version-firebase-billOfMaterials" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "version-androidx-appcompat" }
androidx-media = { module = "androidx.media:media", version.ref = "version-androidx-media" }
androidx-constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "version-androidx-constraint" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "version-library-ktx" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "version-androidx-lifecycle" }

exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "version-library-exoplayer" }

libraries-multidex = { module = "androidx.multidex:multidex", version.ref = "version-androidx-multidex" }
libraries-material-dialogs = { module = "com.afollestad.material-dialogs:core", version.ref = "version-library-material-dialogs" }
libraries-leak = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "version-library-leak" }
libraries-timber = { module = "com.jakewharton.timber:timber", version.ref = "version-library-timber" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Test dependencies
test-junit = { module = "junit:junit", version.ref = "version-junit" }
test-mockk = { module = "io.mockk:mockk", version.ref = "version-mockk" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "version-mockk" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "version-robolectric" }
test-androidx-core = { module = "androidx.test:core", version.ref = "version-androidx-test-core" }
test-androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "version-androidx-test-core" }
test-androidx-runner = { module = "androidx.test:runner", version.ref = "version-androidx-test-runner" }
test-androidx-rules = { module = "androidx.test:rules", version.ref = "version-androidx-test-rules" }
test-androidx-ext-junit = { module = "androidx.test.ext:junit", version.ref = "version-androidx-test-ext-junit" }
test-androidx-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "version-androidx-test-ext-junit" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "version-espresso" }
test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "version-espresso" }
test-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "version-androidx-arch-core" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "version-coroutines-test" }
test-fragment = { module = "androidx.fragment:fragment-testing", version.ref = "version-androidx-fragment-testing" }

[plugins]

android-application = { id = "com.android.application", version.ref = "version-plugin-agp" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "version-kotlin-bom" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "version-kotlin-bom" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "version-kotlin-bom" }
android-gradle = { id = "com.android.tools.build:gradle", version.ref = "version-plugin-agp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "version-plugin-crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "version-plugin-google" }
